### ISSUE TITLE
Add fish keywords and builtins

### ISSUE THREAD

**Issue by terlar** [Alexander-Miller/company-shell#10]
Currently I have added something like this:

```
(add-to-list 'company-keywords-alist
             (cons 'fish-mode (append fish-builtins
                                      fish-keywords))))

(setq-local company-backends '((company-keywords
                                company-shell
                                company-fish-shell)))
```

I wonder if there is interest to add a simple backend to this package including the `fish-builtins` and `fish-keywords` in the `company-fish-shell` completion list or if they belong in a separate completion.

I think it would be nice to have these included in this package somehow. What do you think?

**Comment by Alexander-Miller** [comment]
Good idea. I'll add a third backend.

**Comment by Alexander-Miller** [comment]
All right, now that I've had a look a new backend seems pretty much overkill. As far as I can tell the only comletions missing are those provided by `builtin -n`, which is really not that many.

I've now added those to the fish shell backend and pushed it to the `builtins` branch. Go ahead and try it out, see if anything's missing. I've run a quick comparison against fish-mode's keywords and builtins and did not find anything amiss, so if you say nothing's missing I'll push to master.

**Comment by Alexander-Miller** [comment]
Well, it's been a couple of days now, so I went ahead and pushed the changes to master.

I'll be closing this issue now. Feel free to reopen if there's anything missing.

**Comment by terlar** [comment]
Sorry for not giving feedback, I will try it out, now on the master branch :+1:
