### ISSUE TITLE
Documentation (man page) buffer contains lots of ^H characters, making it difficult to read

### ISSUE THREAD

**Issue by ackalker** [Alexander-Miller/company-shell#11]
On my system (Void Linux), requesting documentation on a candidate gives me a buffer with text which is hard to read because it is littered with `^H` control characters.
A snippet of the `ls` man page (Github markdown doesn't do it justice):
```
LS(1)                            User Commands                           LS(1)



NNAAMMEE
       ls - list directory contents

SSYYNNOOPPSSIISS
       llss [_O_P_T_I_O_N]... [_F_I_L_E]...
```

I've found that this is because `man ls` tries to emulate bold and underlined characters by backspacing and overstriking, even if standard output is not a terminal (and even if the `TERM` environment variable is set to `dumb`). I believe this is due to Void Linux using `mdocml` (`mandoc`) package by default, instead of the (more common?) `man-db` package.

One solution is to clean this cruft from the documentation buffer (similar to what Emacs function `Man-cleanup-manpage` does), but I think an easier solution is to simply use Emacs' built-in `man` function (which doesn't exhibit this issue) to create the buffer with the man page, similar to what the `company-elisp` backend does (it calls one of `describe-function`, `describe-variable`, etc., which all create their own documentation buffers).

**Comment by ackalker** [comment]
Emacs `man` returns a buffer object, which I think can be used directly with a `doc-buffer` clause in the backend.

```elisp
ELISP> (save-window-excursion (man "ls"))
#<buffer *Man ls*>
```

One remaining issue: detecting that a man page doesn't exist.

Emacs `man` will close its documentation window and bury its buffer if a man page doesn't exist, but it runs the system `man` command as an asynchronous process, so one has to wait a bit for it to complete.
```elisp
ELISP> (let ((buf (save-window-excursion (man "blub")))) (buffer-live-p buf))
t
ELISP> (let ((buf (save-window-excursion (man "blub")))) (sit-for 1) (buffer-live-p buf))
nil
```

I've thought of using `whatis` to check for the existence of a man page, but a problem with that is that `whatis` does a case-insensitive substring search by default, and the `mandoc` and `man-db` versions of `whatis` use different syntax for searching for an exact match.

**Comment by Alexander-Miller** [comment]
> One solution is to clean this cruft from the documentation buffer (similar to what Emacs function Man-cleanup-manpage does), but I think an easier solution is to simply use Emacs' built-in man function

I tried both, and using `Man-clean-manpage` was the by far easier solution. I just needed to send my doc buffer through it, and it would come out clean. Meanwhile using emacs' `man` function was full of gotchas. You need to manually wait until the man page buffer is actually built and formatted or the doc string popup won't show. `man` will also keep around the buffer it has created, so it needs to be deleted, too.

I've uploaded proofs of concept for both solutions for you to test, to the `man-cleanup` and `man-page-format` branch respectively. Let me know how they work out.

**Comment by ackalker** [comment]
Thanks for the quick reply, I will certainly try your suggestions. I also have some of my own, perhaps I will make a PR later.

**Comment by ackalker** [comment]
I've tested both branches (thanks again!). Both work well, I don't have the spurious characters in man pages anymore.

`man-cleanup` branch is very fast, but lacks the nice fontification which `man-page-format` branch has. Also when I installed from `man-cleanup` branch, I got this byte-compiler warning:
```
Warning (bytecomp): the function ‘Man-cleanup-manpage’ is not known to be defined.
```
and then when I called up documentation for the first time, it gave me an error:
```
company-call-backend-raw: Company: backend company-shell error "Symbol’s function definition is void: Man-cleanup-manpage" with args (doc-buffer printenv)
```
I'm afraid the reason for this is that `Man-cleanup-manpage` may not be a function meant for public use. The error is easy enough to fix: add `(require 'man)` (or perhaps better yet, an `autoload`) to `company-shell.el`. I am a bit more worried about future breakage when Emacs developers decide to change the implementation in `man.el`.
If we choose to use the public function `man`, we may have a bit more leverage when we ask Emacs developers to add extra features to it (like support for synchronous operation, output to a string, etc.).

`man-page-format` branch of course has the nice fontification of `M-x man` (which personally I like best). ~~I haven't tested it with `company-quickhelp` yet though, I hope it works with that as well.~~ It works with `company-quickhelp-mode` as well.
It is a bit slower than `man-cleanup`, because of the wait for the async process. Also, when there is no man page for a command, I get an empty buffer instead of the `man: No entry for print_sum in the manual.` which I get with the `man-cleanup` branch.

Both solutions are fine with me, personally I would prefer `man-page-format` because of the nice fontification and use of 'public' `man` function,  even when it is slightly slower. I gladly leave it up to you to decide which (if any) you want to use.

**Comment by Alexander-Miller** [comment]
> I am a bit more worried about future breakage when Emacs developers decide to change the implementation in man.el.

It's interactive and comes with a doc string. That's public enough I guess. It also consits only of regex deletions without any deep dependencies, so can be reimplemented easily enough if need be.

> and then when I called up documentation for the first time, it gave me an error:

As you said, autoload solves this problem.

> Also, when there is no man page for a command, I get an empty buffer instead of the man: No entry for print_sum in the manual.

I'll have a look.

> I gladly leave it up to you to decide which (if any) you want to use.

And *I* am going to leave it up to *you*. No size fits all, so the user gets to decide. Code should be ready in a couple of days, in the meantime here's a preview. Let me know if the doc makes sense and I've covered everything:

(defvar company-shell-man-post-process 'none
  "Indicates how company shell processess the man pages it uses for dock strings (if
those man pages exist). Post-process methods, if any are selected, provide 2
benefits:

1) Clean the man page of any visible escape codes (you'll know it when you see it)
2) Fontify the man pages via `Man-mode' (affects only company's own doc buffers
   and *not* the popups of `company-quickhelp-mode')

Possible values are as follows:

'none:      (Default) No special formatting takes place. Simply grab a man page's
            raw content.
            Pro: fastest
            Con: no fontification, no escape code cleanup

'manual:    Grab a man page's raw content and then manually remove any visible
            escape codes.
            Pro: cleans escape codes, faster than using 'emacs-man
            Con: no fontification

'emacs-man: Instead of spawning a man shell command use emacs' builtin `man'
            function.
            Pro: cleans escape codes, provides fontification
            Con: slowest - need to wait for emacs to format & fontify, delay
                 should not be longer than a second

Any other value is treated as 'none")

**Comment by Alexander-Miller** [comment]
Clean and documented fix is up on the `dev` branch, ready for testing. Note that the new variable is now called `company-shell-man-page-handling`. IMO it's a better fit.

**Comment by Alexander-Miller** [comment]
Been a while now, you still around?

Even if the issue is no longer relevant for you, I'd still like to know if my solution actually works w.r.t. cleaning up those ^H's before I push to master.

**Comment by Alexander-Miller** [comment]
I just looked over the changes again and decided to drop the use of the builtin man-mode - I just cannot get it to consistently work with company-quickhelp.

The change is up on master now. I'll close up here on account of inactivity.
