### ISSUE TITLE
Question: should backend return nil if no candidates?

### ISSUE THREAD

**Issue by jsirex** [Alexander-Miller/company-shell#14]
In this case:
```
(add-to-list 'company-backends 'company-shell)
(add-to-list 'company-backends 'company-shell-env)
```
When I try to complete company only completes using `company-shell-env` backend and ignores others.
It is probably because backend must return `nil` and other backends get tried?

As workaround I grouped them together as:
```
(add-to-list 'company-backends '(company-shell company-shell-env company-capf))
```
Now, I'm wonder is it actually workaround or by design?

**Comment by Alexander-Miller** [comment]
>  It is probably because backend must return nil and other backends get tried?

I remember asking the same question a couple years ago myself, thinking it's a bug that `company-files` won't do anything when it's preceded by `company-capf`. 
Long story short: you're right, this is how backends are designed to work, and grouping them is the correct approach to get completions from all.
