### ISSUE TITLE
Does this package support bash?

### ISSUE THREAD

**Issue by hongyi-zhao** [Alexander-Miller/company-shell#18]
Today, I noticed this package from [here](https://melpa.org/#/company-shell), but I'm not sure if it supports bash. Any hints will be highly appreciated.

Regards,
HZ

**Comment by Alexander-Miller** [comment]
Yes, the `company-shell` [backend](https://github.com/Alexander-Miller/company-shell#backends) will pick up everything in your PATH, that includes all the bash commands in /usr/bin.

**Comment by hongyi-zhao** [comment]
If so, for bash, what `company-backends` configuration should be used? I've checked the guidance [here](https://github.com/Alexander-Miller/company-shell#setup) and [here](https://github.com/Alexander-Miller/company-shell#configuration), but I still don't quite understand.
