### ISSUE TITLE
Disable company-shell in comments?

### ISSUE THREAD

**Issue by sandinmyjoints** [Alexander-Miller/company-shell#21]
I'm getting completion suggestions from company-shell when writing comments. Is it possible to add a flag to disable that behavior?

**Comment by Alexander-Miller** [comment]
Not right now, but it should be an easy change. I can add it in a bit.

**Comment by sandinmyjoints** [comment]
Thanks, no rush! And thank you for this package, treemacs, and the other emacs packages you maintain!

**Comment by Alexander-Miller** [comment]
You can now disable completions in comments via `company-shell-complete-in-comments`.

**Comment by sandinmyjoints** [comment]
Thanks!
