### ISSUE TITLE
Awesome, up on package?

### ISSUE THREAD

**Issue by fxfactorial** [Alexander-Miller/company-shell#3]
This is great, thanks. Can you package this up so that `package-install` will play nicely with it?

**Comment by Alexander-Miller** [comment]
MELPA integration is now on its way: https://github.com/milkypostman/melpa/pull/3562

**Comment by Alexander-Miller** [comment]
company-shell is merged now. Package.el should be able to install it (soon). Let me know if everything's working the way it's supposed to.

Also note the architectural changes - `$PATH` and fish-shell completions are now both provided by its own backend.

**Comment by gopar** [comment]
It's in MELPA now and works.

**Comment by fxfactorial** [comment]
Nice! Thank you!
