### ISSUE TITLE
Running `cmd --help` for fetching docstring isn't safe

### ISSUE THREAD

**Issue by mattiasb** [Alexander-Miller/company-shell#5]
Running `cmd --help` for fetching the docstring (even though you only do it when there's no man page) isn't safe. There is no way to know that the command actually takes a `--help` flag and it might do something harmful (or just not exit) when executed. 

As a test I made a little script that I executed in a Fedora 23 live installer in a virtual machine:

``` shell
#!/bin/bash

for i in /usr/bin/*; do
        echo -e "\n\n----------------------------------------------\n\n"
        echo -e "${i}:\n\n"
        "${i}" --help
done
```

I'd advice against running the above on your main machine. :)
Running this script I can see that some of the cups-\* commands will start wizards or start looking for printers etc. when run with `--help`

For an example of weirdness that can happen, triggered from inside emacs, see [this clip](https://youtu.be/H0HiWs2kako).

**Comment by Alexander-Miller** [comment]
And here I thought a simple 100 LOC plugin would be free from evil corner-cases of DOOM.

Now, I'd rather not completely cut away half the possible doc-strings, so here's the plan:
- run `foo --help` with a 1s timeout, that's enough to get the doc-string, but will quickly close any accidental spawns
- run `foo --help` in a restricted shell to further cut down the potential for accidents
- make the whole thing opt in, with a big fat warning sign attached

I think it's a fair assumption that this is a sufficient amount of prevention, considering this package is used by people who write shell scripts using a custom plugin for a custom plugin for emacs.

If you (or someone else reading this) would like to help me put my ideas to the test: I've pushed a preliminary commit that implements the first 2 points to the branch unsafe-help.

**Comment by mattiasb** [comment]
That sounds good enough for me! Also I forgot to say yesterday: thanks for a nice package, I really like it! :)

**Comment by Alexander-Miller** [comment]
Thanks for the compliments.

The patch is pushed now.

**Comment by mattiasb** [comment]
\o/
