### ISSUE TITLE
add `shell-mode` to `company-shell-modes`

### ISSUE THREAD

**Issue by waymondo** [Alexander-Miller/company-shell#6]
i'm glad to see a modern shell company backend popup up. thanks for this. is there any reason not to have `shell-mode` be a default member of `company-shell-modes`?

**Comment by Alexander-Miller** [comment]
I run fish shell through multi-term, so I simply didn't think of it.

I've pushed a fix now.

**Comment by waymondo** [comment]
no worries! thanks.
