### ISSUE TITLE
Company quickhelp for company-shell backend.

### ISSUE THREAD

**Issue by ReneFroger** [Alexander-Miller/company-shell#7]
I noticed you use `company-quickhelp` in the screenshots, but I couldn't get the same quickhelp window in `shell-mode` and in `eshell-mode`.

As configuration I set it up as following with empty Emacs config:

```

    (use-package company
    :diminish company-mode
    :config
    (global-company-mode 1)
    (setq use-package-always-ensure     nil  ;; Disable completion from Company backend for use-package
            company-idle-delay            0.0  ;; 0.1 second delay before the pop-up appears
            company-minimum-prefix-length 1    ;; you only need to enter one character in a buffer before auto-completion starts
            company-minimum-prefix-length 2
            )

    (use-package company-quickhelp
    :config
    (company-quickhelp-mode 1)
    (setq company-quickhelp-delay 0.1)
    )


    (use-package company-shell
    :defer 3
    :config
    (add-to-list 'company-backends 'company-shell)
    )


```

So I began to wonder what for setup you use to get company quickhelp in eshell/shell mode. Could you tell me where I went wrong?

**Comment by Alexander-Miller** [comment]
Check your mode-line for the active backend when the diminish is disabled. Shell-mode already receives company completions through company-capf which is probably what you're seeing. Manually invoking company-shell should work. If so I recommend you run

`(add-hook 'shell-mode-hook (lambda () (setq-local company-backends '((company-shell company-files)))))`

That'll get you a combined backend to complete both commands and file paths without one blocking the other as company usually does.

**Comment by ReneFroger** [comment]
I think you're confusing this question with another question. I already use the same setup:

```
   (add-hook 'eshell-mode-hook
          (lambda ()
          (set (make-local-variable 'company-backends)
                  '((company-shell company-eshell-history)))))
```

The reason that I use a different setup above in my opening post, is to make it easy for you to have a standard setup as in the manual of `company-shell` to figure out where it went wrong with the quickhelp.

So I believe you're reading the question wrong ..?

**Comment by Alexander-Miller** [comment]
I cannot know what your setup actually looks like, I know only what you tell me.

Let's start debugging then.
- What is the value of company-backends when you run eshell?
- Does manually calling company-shell work?
- Is company-shell the active backend? You'll know its company-shell when you see the path annotation.
- If company-shell is the backend used, does manaully triggering company-quickhelp work? Try something like `(define-key company-active-map (kbd "C-l")   'company-quickhelp-manual-begin)
  `.

**Comment by Alexander-Miller** [comment]
Another question:
- Does company-quickhelp work with other backends?

**Comment by ReneFroger** [comment]
Sorry, I thought you was talking about company-backends. Which worked fine for me, and I was targeting company quickhelp where I see no visible window from quickhelp.
- What is the value of company-backends when you run eshell?

```
 Value: (company-wsd-mode
      (company-bbdb :with company-yasnippet)
      (company-nxml :with company-yasnippet)
      (company-css :with company-yasnippet)
      (company-eclim :with company-yasnippet)
      (company-semantic :with company-yasnippet)
      (company-clang :with company-yasnippet)
      (company-xcode :with company-yasnippet)
      (company-cmake :with company-yasnippet)
      (company-capf :with company-yasnippet)
      (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
      (company-oddmuse :with company-yasnippet)
      (company-files :with company-yasnippet)
      (company-dabbrev :with company-yasnippet)
      (company-yasnippet :with company-yasnippet)
      (company-etags :with company-yasnippet)
      (company-gtags :with company-yasnippet))

```

The weird thing is that I get completion suggestions from `company-shell` and `company-eshell-history` backends, while I don't see it the backends in the <kbd>C-h v</kbd> `company-backends` when I'm in eshell.
- Does manually calling company-shell work?

When <kbd>M-x</kbd> `company-shell` in Eshell, I get the message: `Cannot complete at point` when it's on a blank input. When I type some characters, and call company-shell again, I get the same completion candidates that were already suggested by company earlier in a completion popup.
- Is company-shell the active backend? You'll know its company-shell when you see the path annotation.

Could you explain that? Where could I see the path annotation? As in `/home/my-name/..`, then I see the directories suggested in completion popup.
- If company-shell is the backend used, does manaully triggering company-quickhelp work? Try something like (define-key company-active-map (kbd "C-l") 'company-quickhelp-manual-begin) .

When I type `gr` in Eshell, I see the completion candidates in popup like  `grab`, `graf`, `gressive`, `group`. Then calling `company-quickhelp-manual-begin` with <kbd>C-l</kbd> after evaluating your code snippet. I see no popup from quickhelp. 
- Does company-quickhelp work with other backends?

I don't have see company-quickhelp with other backends. So I assume not (but this is not tested thoroughly, because company-shell seems the only backend where quickhelp could be applied).

**Comment by Alexander-Miller** [comment]
> Could you explain that? Where could I see the path annotation?

In my screenshot it's the part in red that says Fish Function and /usr/bin

> because company-shell seems the only backend where quickhelp

It also works with company-capf in emacs-lisp-mode.

If company-shell is not part of company-backends then it's not going to do anything and the completions you see are from company-capf. You need to make sure that company-shell is not being blocked by anything, which will happen with the clean config you've first posted. 

When I run the proper hooks to set up my company-backends everything works for me in both shell and eshell modes, and your company-backends clearly indicates that something's amiss.

Finally make sure you use the most recent version of company-shell. I've made a few changes since the /r/emacs thread - including adding (e)shell mode to the list of modes company-shell will complete in. Take a look at the content of company-shell-modes to check.

**Comment by ReneFroger** [comment]
Alexander, I updated the `company-shell` with MELPA, where your changes are included via MELPA.

And suddenly, I get the quickhelp popups in Eshell with company with `company-shell`. I changed nothing to my setup above. So it seems this issue is solved now, with the recent changes to `company-shell`.

I really appreciate your help in this case, thanks for that! Und ich wünsche Ihnen einen schönes Wochenende!

**Comment by Alexander-Miller** [comment]
I guess you've been using an older version where company-shell was still set to ignore (e)shell-mode and the completions you saw were from company-capf.

Be sure to read up on the new `company-shell-use-help-arg`, it's what passes as a major change in a package of this size.

> Und ich wünsche Ihnen einen schönes Wochenende! 

Gleichfalls.
